budgets/urls.py
from django.urls import path
from . import views


app_name = "budgets"


urlpatterns = [
    path("", 
         views.BudgetTableView.as_view(), 
         name="budgets"
    ),
    path(
        "add_budget/",
        views.AddBudgetView.as_view(),
        name="add_budget",
    ),
    path(
        "delete_budget/",
        views.delete_budget,
        name="delete_budget",
    ),
    path(
        "edit/<int:pk>/",
        views.BudgetUpdateView.as_view(),
        name="edit_budget",
    ),
]

categories/urls.py
from django.urls import path
from . import views


app_name = "categories"


urlpatterns = [
    path("", 
         views.CategoryTableView.as_view(), 
         name="categories"
    ),
    path(
        "add_category/",
        views.AddCategoryView.as_view(),
        name="add_category",
    ),
    path(
        "delete_categories/",
        views.delete_categories,
        name="delete_categories",
    ),
    path(
        "edit/<int:pk>/",
        views.CategoryUpdateView.as_view(),
        name="edit_category",
    ),
]

my_budget_planner_with_snake/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import AuthRedirectView


urlpatterns = [
    path('', AuthRedirectView.as_view(pattern_name="login")),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('categories/', include('categories.urls')),
    path('budgets/', include('budgets.urls')),
    path('transactions/', include('transactions.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

transactions/urls.py
from django.urls import path
from . import views


app_name = "transactions"


urlpatterns = [
    path("", 
         views.TransactionTableView.as_view(), 
         name="transactions"
    ),
    path(
        "add_single/",
        views.AddSingleTransactionView.as_view(),
        name="add_single",
    ),
    path(
        "delete_transactions/",
        views.delete_transactions,
        name="delete_transactions",
    ),
    path(
        "add_repeatable/",
        views.AddRepeatableTransactionView.as_view(),
        name="add_repeatable",
    ),
    path(
        "edit/<int:pk>/",
        views.TransactionUpdateView.as_view(),
        name="edit_transaction",
    ),
]

transactions/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from djmoney.models.fields import MoneyField
from djmoney.models.validators import MinMoneyValidator


class RepeatableTransaction(models.Model):
    # Choises for recurrence_type field
    class RecurrenceTypes(models.TextChoices):
        DAILY = "DAILY", _("Daily")
        WEEKLY = "WEEKLY", _("Weekly")
        MONTHLY = "MONTHLY", _("Monthly")
        ANNUALLY = "ANNUALLY", _("Annually")

    # Fields
    description = models.CharField(max_length=255, blank=True)
    base_amout = MoneyField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default_currency="PLN",
        validators=[MinMoneyValidator(0)],
    )
    start_date = models.DateField(default=timezone.now, null=False)
    end_date = models.DateField(default=timezone.now, null=False)
    recurrence_type = models.CharField(
        max_length=10,
        choices=RecurrenceTypes.choices,
        default=RecurrenceTypes.DAILY,
        null=False,
    )
    recurrence_value = models.IntegerField(default=1, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        "categories.Category",
        on_delete=models.CASCADE,
        default=None,
        null=False,
    )
    type = models.ForeignKey(
        "categories.Type",
        on_delete=models.CASCADE,
        default=None,
    )
    budget = models.ForeignKey('budgets.Budget', on_delete=models.CASCADE, default=None)

    # Meta class
    class Meta:
        verbose_name = "RepeatableTransaction"
        verbose_name_plural = "RepeatableTransactions"

    # Methods
    def __str__(self):
        return self.description


class Transaction(models.Model):
    # Fields
    description = models.CharField(max_length=255, blank=True)
    amount = MoneyField(
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False,
        default_currency="PLN",
        validators=[MinMoneyValidator(0)],
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    execution_date = models.DateField(default=timezone.now)
    is_executed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        "categories.Category",
        on_delete=models.CASCADE,
        default=None,
    )
    type = models.ForeignKey(
        "categories.Type",
        on_delete=models.CASCADE,
        default=None,
    )
    repeatable_transaction = models.ForeignKey(
        RepeatableTransaction, blank=True, null=True, on_delete=models.CASCADE
    )
    budget = models.ForeignKey('budgets.Budget', on_delete=models.CASCADE)

    # Meta class
    class Meta:
        verbose_name = "Transaction"
        verbose_name_plural = "Transactions"

    # Methods
    def __str__(self):
        return self.description
    
    def get_absolute_url(self):
        return reverse('transactions:transaction_detail', args=(self.id,))

transactions/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from djmoney.forms.widgets import MoneyWidget
from .models import RepeatableTransaction, Transaction


class AddSingleTransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        currency_choices = (
            ("PLN", "PLN"),
            ("USD", "USD"),
            ("EUR", "EUR"),
        )
        
        fields = (
            "description",
            "amount",
            "execution_date",
            "is_executed",
            "category",
            "type",
            "budget",
        )
        labels = {
            "type": _("Type"),
            "amount": _("Amount"),
            "category": _("Category"),
            "budget": _("Budget"),
            "execution_date": _("Execution date"),
            "is_executed": _("Is executed?"),
            "description": _("Description")
        }
        widgets = {
            "type": forms.widgets.Select(attrs={"required": True}),
            "amount": MoneyWidget(
                amount_widget=forms.widgets.NumberInput(
                    attrs={
                        "min":0,
                        "step":0.01,
                        "placeholder": _("Amount"),
                        "class": "form-control"},
                    
                ),
                currency_widget=forms.widgets.Select(
                    attrs={"class": "form-select"},
                    choices=currency_choices),
                default_currency = "PLN"
                ),
            "description": forms.widgets.Textarea(attrs={"rows": "3"})
        }
        
            
class AddRepeatableTransactionForm(forms.ModelForm):
    class Meta:
        model = RepeatableTransaction
        currency_choices = (
            ("PLN", "PLN"),
            ("USD", "USD"),
            ("EUR", "EUR"),
        )
        
        fields = (
            "description",
            "base_amout",
            "start_date",
            "end_date",
            "recurrence_type",
            "recurrence_value",
            "category",
            "type",
            "budget",
        )
        labels = {
            "type": _("Type"),
            "base_amout": _("Base Amount"),
            "category": _("Category"),
            "budget": _("Budget"),
            "start_date": _("From date"),
            "end_date": _("To date"),
            "recurrence_type": _("Period type"),
            "recurrence_value": _("Period lenght"),
            "description": _("Description")
        }
        widgets = {
            "type": forms.widgets.Select(attrs={"required": True}),
            "base_amout": MoneyWidget(
                amount_widget=forms.widgets.NumberInput(
                    attrs={
                        "min":0,
                        "step":0.01,
                        "placeholder": _("Amount"),
                        "class": "form-control"},
                    
                ),
                currency_widget=forms.widgets.Select(
                    attrs={"class": "form-select"},
                    choices=currency_choices),
                default_currency = "PLN"
                ),
            "recurrence_value": forms.widgets.NumberInput(
                    attrs={
                        "min":0,
                        "step":1,
                        "placeholder": _("Amount"),
                        "class": "form-control"},
                    
                ), 
            "description": forms.widgets.Textarea(attrs={"rows": "3"})
        }
        validators = {
            "recurrence_value": [
                MinValueValidator(1), 
                MaxValueValidator(366)
            ]
        }
        
    def clean_recurrence_value(self):
        max_values = {
            'DAILY': 1,
            'WEEKLY': 7,
            'MONTHLY': 31,
            'ANNUALLY': 366,
        }
        choice = self.cleaned_data.get('recurrence_type')
        max_value = max_values.get(choice)
        number = self.cleaned_data.get('recurrence_value')
        if number > max_value:
            raise forms.ValidationError(f'Maksymalna dozwolona wartość dla opcji {choice} to {max_value}.')
        return number

transactions/views.py
from __future__ import annotations
import json
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import AddSingleTransactionForm, AddRepeatableTransactionForm
from .models import Transaction, RepeatableTransaction
from categories.models import Type, Category, UserCategory


class TransactionMixin:
    """A mixin for views that deal with transactions."""

    def get_context(self, request, form=None):
        """Generate a dictionary with data to pass to the template.

        Args:
            request: An HttpRequest object.
            form: An optional Form object.

        Returns:
            A dictionary with the form, back URL, and type-to-category mapping.
        """
        context = {}
        if form:
            context["form"] = form
        else:
            context["form"] = self.form_class()
        context["back_url"] = request.GET.get("back_url", "/transactions/")
        context["type_to_category"] = self.get_categories(request)
        return context

    def get_categories(self, request):
        """Retrieve available categories for each transaction type.

        Args:
            request: An HttpRequest object.

        Returns:
            A JSON-formatted string representing a dictionary mapping transaction types
            to lists of available categories.
        """
        types = Type.objects.all()
        
        # user categories union with default 
        user_categories = UserCategory.objects.filter(user=request.user)
        categories_user = Category.objects.filter(
            id__in=user_categories.values_list("category_id", flat=True)
        )
        categories_default = Category.objects.filter(default=True)
        categories = categories_user | categories_default
        
        type_to_category = {}
        for t in types:
            category_list = [[c.id, c.category_name] for c in categories if c.type == t]
            type_to_category[t.id] = category_list

        return json.dumps(type_to_category)


@method_decorator(login_required, name="dispatch")
class AddSingleTransactionView(View, TransactionMixin):
    template_name = "transaction/add_transaction_single.html"
    form_class = AddSingleTransactionForm

    def get(self, request):
        return render(request, self.template_name, self.get_context(request))

    def post(self, request):
        # Check if the form is valid
        form = self.form_class(request.POST)
        if form.is_valid():
            # Add new transaction
            transaction = Transaction.objects.create(
                user=self.request.user,
                type=form.cleaned_data["type"],
                amount=form.cleaned_data["amount"],
                category=form.cleaned_data["category"],
                budget=form.cleaned_data["budget"],
                execution_date=form.cleaned_data["execution_date"],
                is_executed=form.cleaned_data["is_executed"],
                description=form.cleaned_data["description"],
            )
            transaction.save()

            # Redirect back to main form
            back_url = request.POST.get("back_url", None)
            if back_url is not None and back_url != "None":
                return redirect(back_url)
            return redirect(request.path)
        else:
            # Form is not valid, display errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field.capitalize()}: {error}")

        return render(request, self.template_name, self.get_context(request, form))


@method_decorator(login_required, name="dispatch")
class AddRepeatableTransactionView(View, TransactionMixin):
    template_name = "transaction/add_transaction_repeatable.html"
    form_class = AddRepeatableTransactionForm

    def get(self, request):
        return render(request, self.template_name, self.get_context(request))

    def post(self, request):
        # Check if the form is valid
        form = self.form_class(request.POST)
        if form.is_valid():
            # Add new transaction
            transaction = RepeatableTransaction.objects.create(
                user=self.request.user,
                type=form.cleaned_data["type"],
                base_amout=form.cleaned_data["base_amout"],
                start_date=form.cleaned_data["start_date"],
                end_date=form.cleaned_data["end_date"],
                recurrence_type=form.cleaned_data["recurrence_type"],
                recurrence_value=form.cleaned_data["recurrence_value"],
                category=form.cleaned_data["category"],
                budget=form.cleaned_data["budget"],
                description=form.cleaned_data["description"],
            )
            transaction.save()

            # Redirect back to main form
            back_url = request.POST.get("back_url", None)

            if back_url is not None and back_url != "None":
                return redirect(back_url)
            return redirect(request.path)

        return render(request, self.template_name, self.get_context(request, form=form))


@method_decorator(login_required, name="dispatch")
class TransactionTableView(View):
    template_name = "transaction/table.html"

    def get(self, request):
        context = {}
        context["single_transactions"] = Transaction.objects.filter(user=request.user)
        context["repeatable_transactions"] = RepeatableTransaction.objects.filter(
            user=request.user
        )
        return render(request, self.template_name, context)


@method_decorator(login_required, name="dispatch")
class TransactionUpdateView(UpdateView, TransactionMixin):
    model = Transaction
    form_class = AddSingleTransactionForm
    template_name = "transaction/edit_single.html"
    success_url = reverse_lazy("transactions:transactions")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["back_url"] = self.request.GET.get("back_url", "/transactions/")
        context["type_to_category"] = self.get_categories(self.request)
        return context


def delete_transactions(request) -> JsonResponse[dict]:
    """
    Deletes the selected categories from the database. Uses AJAX equest form template
    """
    if request.method == "POST":
        ids = request.POST.getlist("ids[]")
        if request.POST.getlist("table")[0] == "table_single":
            Transaction.objects.filter(id__in=ids).delete()
        else:
            RepeatableTransaction.objects.filter(id__in=ids).delete()
        return JsonResponse({"success": True})
    else:
        return JsonResponse({"success": False, "message": "Invalid request method"})

transactions/templates/transaction/add_transaction_repeatable.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}BP | Add repeatable{% endblock %}


{% block content %}
<div class="container form-container  mt-5">
    <div class="p-3 bg-white border border-light rounded shadow">
        <div class="row px-2">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}
            <span class="mb-2 border-bottom border-2">
                <h1 class="fs-3">Add repeatable transaction</h1>
            </span>
            <form action="." method="post">
                {% csrf_token %}
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.budget.name}}" class="form-label">{{form.budget.label}}</label>
                        <div class="input-group">
                            {{form.budget|add_class:"form-select"}}
                            <a href="{% url 'budgets:add_budget' %}?back_url={{ request.path }}"
                                class="btn btn-outline-secondary btn-sm"><i class="bi bi-plus-circle fs-5"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.type.name}}" class="form-label">{{form.type.label}}</label>
                        {{form.type|add_class:"form-select"}}
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.category.name}}" class="form-label">{{form.category.label}}</label>
                        <div class="input-group">
                            {{form.category|add_class:"form-select"}}
                            <a href="{% url 'categories:add_category' %}?back_url={{ request.path }}"
                                class="btn btn-outline-secondary btn-sm"><i class="bi bi-plus-circle fs-5"></i></a>
                        </div>
                    </div>
                </div>

                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.base_amout.name}}" class="form-label">{{form.base_amout.label}}</label>
                        <div class="input-group">
                            {{form.base_amout}}
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col col-6">
                        <label for="{{form.start_date.name}}" class="form-label">{{form.start_date.label}}</label>
                        <div class="">
                            {{form.start_date|add_class:"form-control"|attr:"type:date"|attr:"placeholder:yyyy-mm-dd"}}
                        </div>
                    </div>
                    <div class="col col-6">
                        <label for="{{form.end_date.name}}" class="form-label">{{form.end_date.label}}</label>
                        <div class="">
                            {{form.end_date|add_class:"form-control"|attr:"type:date"|attr:"placeholder:yyyy-mm-dd"}}
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col col-6">
                        <label id="label_{{form.recurrence_type.name}}" for="{{form.recurrence_type.name}}"
                            class="form-label">{{form.recurrence_type.label}}</label>
                        <div class="">
                            {{form.recurrence_type|add_class:"form-control"}}
                        </div>
                    </div>
                    <div class="col col-6">
                        <label id="label_{{form.recurrence_value.name}}" for="{{form.recurrence_value.name}}"
                            class="form-label">{{form.recurrence_value.label}}</label>
                        <div class="">
                            {{form.recurrence_value|add_class:"form-control"}}
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.description.name}}" class="form-label">{{form.description.label}}</label>
                        <div class="">
                            {{form.description|add_class:"form-control"}}
                        </div>
                    </div>
                </div>
                <div class="row pt-4">
                    <div class="d-grid gap-2 col-6 mx-auto" style="width: 100%">
                        <button type="submit" class="btn btn-primary">Add</button>
                        <a href="{{ back_url }}" class="btn btn-outline-secondary">Cancel</a>
                    </div>
                </div>
                <input type="hidden" name="back_url" value="{{ back_url }}">
            </form>
            <script src="{% static 'js/change_labels.js' %}"></script>
            <script>
                changeLabelValue("id_{{form.recurrence_type.name}}", "label_{{form.recurrence_value.name}}", "id_{{form.recurrence_value.name}}")
            </script>
        </div>
    </div>
</div>
<script type=text/javascript>
    var type_to_category = '{{ type_to_category|escapejs }}';
</script>
<script src="{% static 'js/type_category_map.js' %}"></script>
{% endblock content %}

transactions/templates/transaction/add_transaction_single.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}BP | Add single{% endblock %}


{% block content %}
<div class="container form-container  mt-5">
    <div class="p-3 bg-white border border-light rounded shadow">
        <div class="row px-2">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
            {% endif %}
            <span class="mb-2 border-bottom border-2">
                <h1 class="fs-3">Add transaction</h1>
            </span>
            <form action="." method="post">
                {% csrf_token %}
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.budget.name}}" class="form-label">{{form.budget.label}}</label>
                        <div class="input-group">
                            {{form.budget|add_class:"form-select"}}
                            <a href="{% url 'budgets:add_budget' %}?back_url={{ request.path }}"
                                class="btn btn-outline-secondary btn-sm"><i class="bi bi-plus-circle fs-5"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.type.name}}" class="form-label">{{form.type.label}}</label>
                        {{form.type|add_class:"form-select"}}
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.category.name}}" class="form-label">{{form.category.label}}</label>
                        <div class="input-group">
                            {{form.category|add_class:"form-select"}}
                            <a href="{% url 'categories:add_category' %}?back_url={{ request.path }}"
                                class="btn btn-outline-secondary btn-sm"><i class="bi bi-plus-circle fs-5"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.amount.name}}" class="form-label">{{form.amount.label}}</label>
                        <div class="input-group">
                            {{form.amount|add_class:"form-control"}}
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col col-7">
                        <label for="{{form.execution_date.name}}"
                            class="form-label">{{form.execution_date.label}}</label>
                        <div class="">
                            {{form.execution_date|add_class:"form-control"|attr:"type:date"|attr:"placeholder:yyyy-mm-dd"}}
                        </div>
                    </div>
                    <div class="col col-5 d-flex align-items-center">
                        <div class="form-check">
                            {{form.is_executed}}
                            <label for="{{form.is_executed.name}}"
                                class="form-check-label">{{form.is_executed.label}}</label>
                        </div>
                    </div>
                </div>
                <div class="row pb-2">
                    <div class="col">
                        <label for="{{form.description.name}}" class="form-label">{{form.description.label}}</label>
                        <div class="">
                            {{form.description|add_class:"form-control"}}
                        </div>
                    </div>
                </div>
                <div class="row pt-4">
                    <div class="d-grid gap-2 col-6 mx-auto" style="width: 100%">
                        <button type="submit" class="btn btn-primary">Add</button>
                        <a href="{{ back_url }}" class="btn btn-outline-secondary">Cancel</a>
                    </div>
                </div>
                <input type="hidden" name="back_url" value="{{ back_url }}">
            </form>
        </div>
    </div>
</div>
<script type=text/javascript>
    var type_to_category = '{{ type_to_category|escapejs }}';
</script>
<script src="{% static 'js/type_category_map.js' %}"></script>

{% endblock content %}