budgets/urls.py
from django.urls import path
from . import views


app_name = "budgets"


urlpatterns = [
    path("", 
         views.BudgetTableView.as_view(), 
         name="budgets"
    ),
    path(
        "add_budget/",
        views.AddBudgetView.as_view(),
        name="add_budget",
    ),
    path(
        "delete_budget/",
        views.delete_budget,
        name="delete_budget",
    ),
    path(
        "edit/<int:pk>/",
        views.BudgetUpdateView.as_view(),
        name="edit_budget",
    ),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"


urlpatterns = [

    path(
        "",
        views.DashboardView.as_view(),
        name="dashboard",
    ),
    path('calendar_data/', views.calendar_data, name='calendar_data'),
    path('get_pending_list/', views.get_pending_list, name='get_pending_list')

]

my_budget_planner_with_snake/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import AuthRedirectView


urlpatterns = [
    path('', AuthRedirectView.as_view(pattern_name="login")),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('categories/', include('categories.urls')),
    path('budgets/', include('budgets.urls')),
    path('transactions/', include('transactions.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from __future__ import annotations
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from transactions.models import Transaction
from django.http import JsonResponse


@method_decorator(login_required, name="dispatch")
class DashboardView(View):
    template_name = "dashboard/view.html"

    def get(self, request):
        return render(request, self.template_name)
    

def calendar_data(request):
    transactions = Transaction.objects.filter(user=request.user)
    data = []
    for transaction in transactions:
        data.append({
            'title': transaction.category.category_name,
            'start': transaction.execution_date.isoformat(),
            'description': transaction.description,
            'amount': {
                'amount': str(transaction.amount.amount),
                'currency': str(transaction.amount.currency)
            },
            'type': transaction.type.type_name,
            'color': '#198754' if transaction.type.type_name == "Income" else '#dc3545',
            'budget': transaction.budget.budget_name,
            'created': transaction.created.isoformat(),
            'updated': transaction.updated.isoformat(),
            'is_executed': transaction.is_executed,
            
        })
    return JsonResponse(data, safe=False)
    
    
def get_pending_list(request):
    """Returns a JSON response containing a list of pending transactions.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        JsonResponse: A JSON response containing a list of pending transactions, sorted by execution date. Each transaction is represented as a dictionary with the following keys:
            - title (str): The name of the transaction category.
            - start (str): The execution date of the transaction, in ISO format.
            - description (str): A description of the transaction.
            - amount (dict): A dictionary containing the amount and currency of the transaction, represented as strings.
            - type (str): The name of the transaction type (e.g. "Income" or "Expense").
            - color (str): The color code for the transaction type, "#198754" for income transactions and "#dc3545" for expense transactions.
            - budget (str): The name of the budget associated with the transaction.
            - created (str): The creation date of the transaction, in ISO format.
            - updated (str): The last update date of the transaction, in ISO format.
            - is_executed (bool): True if the transaction has been executed, False otherwise.
            - execution_date (str): The execution date of the transaction, in ISO format.

    Raises:
        None
    """
    pending_transacion = Transaction.objects.filter(is_executed=False, user=request.user).order_by('execution_date')
    data = []
    for transaction in pending_transacion:
        data.append({
            'title': transaction.category.category_name,
            'start': transaction.execution_date.isoformat(),
            'description': transaction.description,
            'amount': {
                'amount': str(transaction.amount.amount),
                'currency': str(transaction.amount.currency)
            },
            'type': transaction.type.type_name,
            'color': '#198754' if transaction.type.type_name == "Income" else '#dc3545',
            'budget': transaction.budget.budget_name,
            'created': transaction.created.isoformat(),
            'updated': transaction.updated.isoformat(),
            'is_executed': transaction.is_executed,
            "execution_date": transaction.execution_date.isoformat()
            
        })
    return JsonResponse(data, safe=False)

dashboard/templates/dashboard/view.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div class="container mt-5">
    <!-- Modat to add new transactions -->
    <div class="modal fade" id="addModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Modalne okno do dodawania nowych transakcji
                </div>
                <div class="modal-footer">
                    <button id="modalClose1" type="button" class="btn btn-secondary"
                        data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal to display details -->
    <div class="modal fade" id="editForm" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p><strong>Description:</strong> <span id="eventDescription"></span></p>
                    <p><strong>Execution date:</strong> <span id="eventStart"></span></p>
                    <p><strong>Amount:</strong> <span id="eventAmountValue"></span></p>
                    <p><strong>Currency:</strong> <span id="eventAmountCurrency"></span></p>
                    <p><strong>Is executed:</strong> <span id="eventIsExecuted"></span></p>
                </div>
                <div class="modal-footer">
                    <button id="modalClose1" type="button" class="btn btn-secondary"
                        data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="p-3 bg-white border border-light rounded shadow">
                <div id="pending_list"></div>
            </div>
        </div>
        <div class="col-8">
            <div class="p-3 bg-white border border-light rounded shadow">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home"
                            aria-selected="true">Calendar</button>
                        <button class="nav-link" id="nav-budget-tab" data-bs-toggle="tab" data-bs-target="#nav-budget"
                            type="button" role="tab" aria-controls="nav-budget" aria-selected="false">Budgets
                            summary</button>
                        <button class="nav-link" id="nav-categories-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-categories" type="button" role="tab" aria-controls="nav-categories"
                            aria-selected="false">Categories summary</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <div class="mt-3" id='calendar'></div>
                    </div>
                    <div class="tab-pane fade show" id="nav-budget" role="tabpanel" aria-labelledby="nav-budget-tab">
                        Comming soon
                    </div>
                    <div class="tab-pane fade show" id="nav-categories" role="tabpanel"
                        aria-labelledby="nav-categories-tab">
                        Comming soon
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,listMonth'

                },
                selectable: true,
                initialView: 'dayGridMonth',
                events: '{% url "dashboard:calendar_data" %}',

                eventClick: function (info) {
                    var modalEditForm = document.getElementById('editForm')
                    modalEditForm.style.display = 'block'
                    modalEditForm.querySelector('#staticBackdropLabel').textContent = info.event.title;
                    modalEditForm.querySelector('#eventStart').textContent = info.event.start.toLocaleString('pl-PL', { day: 'numeric', month: 'numeric', year: 'numeric' });
                    modalEditForm.querySelector('#eventAmountValue').textContent = info.event.extendedProps.amount.amount;
                    modalEditForm.querySelector('#eventAmountCurrency').textContent = info.event.extendedProps.amount.currency;
                    modalEditForm.querySelector('#eventDescription').textContent = info.event.extendedProps.description;
                    modalEditForm.querySelector('#eventIsExecuted').textContent = info.event.extendedProps.is_executed;

                    var modalEditForm = new bootstrap.Modal(modalEditForm);
                    modalEditForm.show();
                },
                select: function (arg) {
                    var addModal = document.getElementById('addModal')
                    var addModal = new bootstrap.Modal(addModal);
                    addModal.show();
                },

            });
            calendar.render();

        });
        const closeBtn1 = document.getElementById('modalClose1');
        closeBtn1.addEventListener('click', () => {
            const eventModal = document.getElementById('staticBackdrop')
            eventModal.style.display = 'none';
        });

    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        // Script to liad json respoinse to pending list
        $(document).ready(function() {
            $.ajax({
                url: 'get_pending_list/',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    var today = new Date();                   
                    var objects = data;
                    var ol = $('<ol></ol>').addClass('list-group');
                    $.each(objects, function(index, object) {
                        var executionDate = new Date(object.execution_date);
                        var li = $('<li></li>').addClass('list-group-item d-flex justify-content-between align-items-start');
                        var div1 = $('<div></div>').addClass('ms-2 me-auto').text(object.title + " | " + object.amount.amount + object.amount.currency + " | " + object.type).append($('<div></div>').append($('<div></div>').text(object.description)));
                        // Change pill color if execution date is smaler then today.
                        if (executionDate > today) {
                            li.append(div1).append($('<span></span>').addClass('badge bg-primary rounded-pill').text(object.execution_date));
                        } else {
                            li.append(div1).append($('<span></span>').addClass('badge bg-danger rounded-pill').text(object.execution_date));
                        }
                        ol.append(li);
                    });
                    $('#pending_list').html(ol);
                },
                error: function(xhr, status, error) {
                    console.log(error);
                }
            });
        });
    </script>
    {% endblock content %}