budgets/urls.py
from django.urls import path
from . import views


app_name = "budgets"


urlpatterns = [
    path("", 
         views.BudgetTableView.as_view(), 
         name="budgets"
    ),
    path(
        "add_budget/",
        views.AddBudgetView.as_view(),
        name="add_budget",
    ),
    path(
        "delete_budget/",
        views.delete_budget,
        name="delete_budget",
    ),
    path(
        "edit/<int:pk>/",
        views.BudgetUpdateView.as_view(),
        name="edit_budget",
    ),
]

categories/urls.py
from django.urls import path
from . import views


app_name = "categories"


urlpatterns = [
    path("", 
         views.CategoryTableView.as_view(), 
         name="categories"
    ),
    path(
        "add_category/",
        views.AddCategoryView.as_view(),
        name="add_category",
    ),
    path(
        "delete_categories/",
        views.delete_categories,
        name="delete_categories",
    ),
    path(
        "edit/<int:pk>/",
        views.CategoryUpdateView.as_view(),
        name="edit_category",
    ),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"


urlpatterns = [

    path(
        "",
        views.DashboardView.as_view(),
        name="dashboard",
    ),
    path('calendar_data/', views.calendar_data, name='calendar_data'),
    path('get_pending_list/', views.get_pending_list, name='get_pending_list')

]

my_budget_planner_with_snake/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import AuthRedirectView


urlpatterns = [
    path('', AuthRedirectView.as_view(pattern_name="login")),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('categories/', include('categories.urls')),
    path('budgets/', include('budgets.urls')),
    path('transactions/', include('transactions.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

transactions/urls.py
from django.urls import path
from . import views


app_name = "transactions"


urlpatterns = [
    path("", 
         views.TransactionTableView.as_view(), 
         name="transactions"
    ),
    path(
        "add_single/",
        views.AddSingleTransactionView.as_view(),
        name="add_single",
    ),
    path(
        "delete_transactions/",
        views.delete_transactions,
        name="delete_transactions",
    ),
    path(
        "add_repeatable/",
        views.AddRepeatableTransactionView.as_view(),
        name="add_repeatable",
    ),
    path(
        "edit/<int:pk>/",
        views.TransactionUpdateView.as_view(),
        name="edit_transaction",
    ),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js"></script>

    
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
</head>

<body class="bg-body-secondary bg-opacity-50">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
        <div class="container d-flex flex-nowrap">
            <a href="{% url 'dashboard:dashboard' %}" class="navbar-brand align-items-center  w-100 ">
                <i class="bi bi-piggy-bank fs-4">&nbsp;</i>
                <span class="fs-4"><b>BUDGET</b>PLANNER</a></span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-grow-1" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a href="{% url 'dashboard:dashboard' %}"
                        class="nav-link text-primary {% if request.path == '/dashboard/' %}active_underline{% endif %}"
                        aria-current="page">
                        <i class="bi bi-clipboard-data fs-4"></i>
                    </a>
                    <a href="{% url 'transactions:transactions' %}"
                        class="nav-link text-primary {% if request.path == '/transactions/' %}active_underline{% endif %}">
                        <i class="bi bi-receipt fs-4"></i>
                    </a>
                    <a href="{% url 'categories:categories' %}"
                        class="nav-link text-primary {% if request.path == '/categories/' %}active_underline{% endif %}"><i
                            class="bi bi-tags fs-4"></i></a>
                    <a href="{% url 'budgets:budgets' %}"
                        class="nav-link text-primary {% if request.path == '/budgets/'  %}active_underline{% endif %}"><i
                            class="bi bi-cash-stack fs-4"></i></a>
                    <a href="{% url 'user_profile' %}"
                        class="nav-link text-primary {% if request.path == '/accounts/user_profile/' %}active_underline{% endif %}"><i
                            class="bi bi-person-circle fs-4"></i></a>
                    <a href="{% url 'logout' %}"
                        class="nav-link text-primary {% if request.path == '/accounts/logout/' %}active_underline{% endif %}"><i
                            class="bi bi-box-arrow-right fs-4"></i></a>
                </div>
            </div>
        </div>
    </nav>
    {% endif %}
    <main>
        {% block content %}

        {% endblock content %}
    </main>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"
        integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.js"></script>
</body>